describe('config.js', () => {
    describe('getTableFromConfig', () => { })
    describe('getCollectionsFromConfig', () => { })
    describe('readJoin', () => { })
    describe('getReferencedColumns', () => { })
    describe('setFullObj', () => { })
    describe('getTables', () => { })
    describe('getTableAccordingToRef', () => { })
    describe('getObjectWithFeildNameForPrimaryKey', () => { })
    describe('getForeignTableAndColumn', () => { })
    describe('convertFieldType', () => { })
    describe('getTabeColumnName', () => { })
})